use `usuarios`;
CREATE TABLE IF NOT EXISTS `User`(
`id` INT PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(100) NOT NULL,
`lastName` VARCHAR(100) NOT NULL,
`mail` VARCHAR(200) NOT NULL,
`password` VARCHAR(200) NOT NULL,
`date`  VARCHAR(200) NOT NULL
)